---
version: 0.3.0
commit: chore(version): :arrow_heading_up: bump to v%.%.%
files:
  README.md:
  - long-dream-core v%.%.%
  - doc/v%.%.%
  package.json:
  - '"version": "%.%.%"'
  ".jsduck.release.json":
  - "(v%.%.%)"
  - doc/v%.%.%
