language: node_js

node_js:
- 0.12

sudo: false

branches:
  only:
    - gh-pages

before_install:
  - npm install -g karma-cli

script:
- npm run lint
- npm run ci

after_success:
- npm run coveralls
