language: node_js

sudo: false

branches:
  only:
    - gh-pages

before_install:
  - npm install -g jshint bower karma-cli
  - bower install
  - bundle install

script:
- npm run lint
- npm run ci

after_success:
- npm run coveralls
